import { ClientStatus, IndustrySector, Continent, Language, DateRange } from './types';
import { LayoutDashboard, Users, Trello, Plus, Search, Filter, Calendar, Mail, Phone, ExternalLink, Trash2, Edit2, Save, X, ChevronRight, Wand2, Map, Briefcase } from 'lucide-react';

export const STATUS_COLORS: Record<ClientStatus, string> = {
  [ClientStatus.OLD]: 'bg-cyan-500/20 text-cyan-400 border-cyan-500/30',
  [ClientStatus.NEW]: 'bg-blue-500/20 text-blue-400 border-blue-500/30',
  [ClientStatus.CONTACTED]: 'bg-yellow-500/20 text-yellow-400 border-yellow-500/30',
  [ClientStatus.NEGOTIATING]: 'bg-orange-500/20 text-orange-400 border-orange-500/30',
  [ClientStatus.ACTIVE]: 'bg-green-500/20 text-green-400 border-green-500/30',
  [ClientStatus.COMPLETED]: 'bg-purple-500/20 text-purple-400 border-purple-500/30',
  [ClientStatus.ARCHIVED]: 'bg-slate-700/50 text-slate-400 border-slate-600',
};

export const SECTOR_OPTIONS = Object.values(IndustrySector);
export const STATUS_OPTIONS = Object.values(ClientStatus);
export const CONTINENT_OPTIONS = Object.values(Continent);

export const DATE_RANGE_OPTIONS: { value: DateRange; labelKey: string }[] = [
  { value: '24h', labelKey: 'last24h' },
  { value: '7d', labelKey: 'last7d' },
  { value: '15d', labelKey: 'last15d' },
  { value: '30d', labelKey: 'last30d' },
  { value: '2m', labelKey: 'last2m' },
  { value: 'any', labelKey: 'anyTime' },
];

export const TRANSLATIONS: Record<Language, any> = {
  en: {
    dashboard: "Dashboard",
    clients: "Clients",
    pipeline: "Pipeline",
    map: "Global Map",
    jobs: "Job Board",
    searchPlaceholder: "Search clients, studios...",
    jobSearchPlaceholder: "Search roles (e.g. Compositor, Rigger)...",
    addClient: "Add Client",
    filterSector: "All Sectors",
    filterContinent: "All Continents",
    totalClients: "Total Clients",
    activeProjects: "Active Projects",
    pendingLeads: "New Contacts",
    followUpDue: "Follow-up Due",
    priorityFollowUps: "Priority Follow-ups",
    recentActivity: "Active Projects",
    proTipTitle: "Pro Tip",
    proTip: "Log every call and email to keep track of your negotiation history.",
    basicInfo: "Basic Info",
    contactDetails: "Contact Details",
    activityLog: "Activity Log",
    saveClient: "Save Client",
    noClients: "No clients found matching your search.",
    name: "Name",
    company: "Company",
    status: "Status",
    sector: "Sector",
    continent: "Continent",
    rate: "Rate / Budget",
    email: "Email",
    phone: "Phone",
    website: "Website",
    location: "Location",
    role: "Role / Title",
    lastContact: "Last Contact",
    nextFollowUp: "Next Follow-Up",
    tags: "Tags",
    notes: "General Notes",
    latitude: "Latitude",
    longitude: "Longitude",
    contactAtStudio: "Contact at Studio",
    applyNow: "Apply Now",
    posted: "Posted",
    noJobs: "No jobs found. Try adjusting filters.",
    deepSearch: "Deep Search (Web)",
    countryFilter: "Country / City",
    source: "Source",
    aiSearchTip: "Using AI to search LinkedIn, Glassdoor, and Studio sites...",
    postedDate: "Posted Date",
    last24h: "Last 24 Hours",
    last7d: "Last 7 Days",
    last15d: "Last 15 Days",
    last30d: "Last 30 Days",
    last2m: "Last 2 Months",
    anyTime: "Any Time",
  },
  es: {
    dashboard: "Panel Principal",
    clients: "Clientes",
    pipeline: "Flujo de Trabajo",
    map: "Mapa Global",
    jobs: "Ofertas de Trabajo",
    searchPlaceholder: "Buscar clientes, estudios...",
    jobSearchPlaceholder: "Buscar roles (ej. Compositor, Rigger)...",
    addClient: "Nuevo Cliente",
    filterSector: "Todos los Sectores",
    filterContinent: "Todos los Continentes",
    totalClients: "Total Clientes",
    activeProjects: "Proyectos Activos",
    pendingLeads: "Nuevos Contactos",
    followUpDue: "Seguimiento Pendiente",
    priorityFollowUps: "Seguimiento Prioritario",
    recentActivity: "Proyectos Activos",
    proTipTitle: "Consejo Pro",
    proTip: "Registra cada llamada y correo para mantener un historial de negociación.",
    basicInfo: "Información Básica",
    contactDetails: "Detalles de Contacto",
    activityLog: "Registro de Actividad",
    saveClient: "Guardar Cliente",
    noClients: "No se encontraron clientes con esa búsqueda.",
    name: "Nombre",
    company: "Empresa",
    status: "Estado",
    sector: "Sector",
    continent: "Continente",
    rate: "Tarifa / Presupuesto",
    email: "Correo",
    phone: "Teléfono",
    website: "Sitio Web",
    location: "Ubicación",
    role: "Rol / Título",
    lastContact: "Último Contacto",
    nextFollowUp: "Siguiente Seguimiento",
    tags: "Etiquetas",
    notes: "Notas Generales",
    latitude: "Latitud",
    longitude: "Longitud",
    contactAtStudio: "Contacto en Estudio",
    applyNow: "Aplicar",
    posted: "Publicado",
    noJobs: "No hay ofertas. Ajusta los filtros.",
    deepSearch: "Búsqueda Profunda (Web)",
    countryFilter: "País / Ciudad",
    source: "Fuente",
    aiSearchTip: "Usando IA para buscar en LinkedIn, Glassdoor y sitios de estudios...",
    postedDate: "Fecha Publicación",
    last24h: "Últimas 24 horas",
    last7d: "Últimos 7 días",
    last15d: "Últimos 15 días",
    last30d: "Últimos 30 días",
    last2m: "Últimos 2 meses",
    anyTime: "Cualquier momento",
  }
};

// Placeholder data for initial load if empty
export const INITIAL_CLIENTS: any[] = [
  {
    id: '1',
    name: 'Sarah Connor',
    company: 'Skynet VFX',
    role: 'VFX Producer',
    email: 'sarah@skynet.com',
    sector: IndustrySector.VFX_FILM,
    status: ClientStatus.ACTIVE,
    statusUpdatedAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(), // 5 days ago
    continent: Continent.NORTH_AMERICA,
    location: 'Los Angeles, USA',
    lat: 34.0522,
    lng: -118.2437,
    notes: 'Working on the cyborg sequence. Needs high-end fluid sims.',
    tags: ['Houdini', 'Fluids'],
    logs: [],
    lastContactDate: new Date().toISOString(),
    nextFollowUpDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: '2',
    name: 'Deckard Cain',
    company: 'Tristram Games',
    role: 'Art Director',
    email: 'cain@tristram.net',
    sector: IndustrySector.GAMES_REALTIME,
    status: ClientStatus.OLD, // Updated from IDLE
    statusUpdatedAt: new Date(Date.now() - 45 * 24 * 60 * 60 * 1000).toISOString(), // 45 days ago
    continent: Continent.EUROPE,
    location: 'London, UK',
    lat: 51.5074,
    lng: -0.1278,
    notes: 'Met at GDC. Interested in UE5 implementation.',
    tags: ['Unreal', 'Realtime'],
    logs: [],
    lastContactDate: new Date(Date.now() - 60 * 24 * 60 * 60 * 1000).toISOString(),
  }
];